[package]
name = "tis2033"
version = "0.1.0"
authors = ["ginkoe"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termion = "*"
colored = "*"